language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xanthoc/docker-react -f frontend/Dockerfile.dev frontend

script:
  - docker run -e CI=true xanthoc/docker-react npm run test
