language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xanthoc/docker-react -f frontend/Dockerfile.dev frontend

script:
  - docker run -e CI=true xanthoc/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "name of s3 bucket created by ebs"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
